# .streamlit/secrets.toml

[connections.snowflake]
account = "JZNPFCP-TX94252"  # Your Snowflake account identifier (replace xxxxxx with your account ID)
user = "naveen"     # Your Snowflake username
password = "Hellop2580@" # Your Snowflake password (replace xxxxxxx with your password)
role = "SYSADMIN"   # The role you want to use
warehouse = "COMPUTE_WH"  # The warehouse you want to use
database = "SMOOTHIES"   # The database you want to use
schema = "PUBLIC"        # The schema you want to use
client_session_keep_alive = true
